# Generated by Django 3.0.4 on 2020-03-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_user_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
