# Generated by Django 3.0.4 on 2020-03-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_auto_20200312_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mins',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
