# Generated by Django 3.0.4 on 2020-03-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_auto_20200313_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='alias',
            field=models.TextField(),
        ),
    ]
