# Generated by Django 3.0.4 on 2020-03-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0008_auto_20200313_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovielogs',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
