# Generated by Django 3.0.4 on 2020-04-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0009_auto_20200320_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovielogs',
            name='rate',
            field=models.CharField(default='1', max_length=64),
        ),
    ]
