# Generated by Django 3.0.4 on 2020-04-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0010_usermovielogs_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMovieLogs',
            new_name='UserLogs',
        ),
    ]
