# Generated by Django 3.0.4 on 2020-04-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0013_auto_20200421_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='intelligence_id',
            new_name='intelligence_id',
        ),
    ]
